### ISSUE TITLE
While compiling i m getting following error, plz check:

### ISSUE THREAD

**Issue by manvirvirk** [Harshit-harit/Image-Classification-4-Persons-using-ANN-and-CNN#2]
ValueError: Cannot feed value of shape (64,) for Tensor 'targets/Y:0', which has shape '(?, 4)'

**Comment by Harshit-harit** [comment]
You are getting this error in spyder or jupyter notebook.

**Comment by manvirvirk** [comment]
I m getting error in jupyter

**Comment by Harshit-harit** [comment]
Send me your screenshot or tell me the line

**Comment by manvirvirk** [comment]
@Harshit-harit  can you plz share your e-mail ID , i can share there. Thanks

**Comment by Harshit-harit** [comment]
Thakurgate@gmail.com

**Comment by manvirvirk** [comment]
Thanks , Please check your mail.
